### ISSUE TITLE
Missing Libraries for Various Plugins

### ISSUE THREAD

**Issue by drewofdoom** [bitwig/bitwig-studio-flatpak#24]
Consolidating a slew of plugin requires that are missing in addition to [issue 17](https://github.com/bitwig/bitwig-studio-flatpak/issues/17). May wish to investigate inserting them into the container as well.

/usr/lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.33' not found
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.29' not found
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.13' not found
libfftw3f.so.3: cannot open shared object file: No such file or directory
liblo.so.7: cannot open shared object file: No such file or directory
libmxml.so.1: cannot open shared object file: No such file or directory
libsecret-1.so.0: cannot open shared object file: No such file or directory <--- [known issue 17](https://github.com/bitwig/bitwig-studio-flatpak/issues/17)
libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory <--- Note that this one is the requirement for [yabridge](https://github.com/robbert-vdh/yabridge)

Most of these should be as simple as adding in the appropriate packages during the build process. It's pretty common for flatpaks to require additional packages be installed during build, as the SDK only contains so many libraries.

Another, possibly more proper way to go about this would be to link with a shared plugin library flatpak, similar to what they're doing for the [LinuxAudio](https://github.com/flathub/flathub/pull/1460) flatpak stuff. In fact, may be worth syncing up with that group, as they may have done most of the work already!

**Comment by abique** [comment]
Why would we add them?
Maybe you want to add them to the freedesktop runtime?

**Comment by drewofdoom** [comment]
The goal of Flatpak is not to include every single thing that would ever be needed by any application ever in the common runtime. Part of the goal of Flatpak is to allow you to include specific libraries with your project. It's not terribly difficult to add packages on top of the runtime you're using for that very reason.

That said, if any of these are common enough, they should definitely go into the runtime. I also take your point that the libraries should be shared, and as such, any that don't make it into the freedesktop runtime could potentially be packaged in a separate "linuxaudio-vst" compatibility flatpak that you could then attach the Bitwig flatpak to in order to "inherit" those libraries.

**Comment by unholyeyebrows** [comment]
Hi - is this issue still being actively looked at? I'm keen to get yabridge working in Bitwig Flatpak but cannot due to the dependency on libboost_filesystem.so. Thanks.

**Comment by abique** [comment]
Hi, we're not looking actively at it, but if you have suggestions regarding the `.yaml` file then we'll listen.

**Comment by robbert-vdh** [comment]
@unholyeyebrows Latest yabridge does not depend on Boost anymore, but that doesn't mean it will start working in Flatpak Bitwig. See https://github.com/robbert-vdh/yabridge/issues/135 for a couple of the blockers for having yabridge work with Flatpak (although with yabridge 4.0's new chainloading the 'no way to keep everything in sync' problem is now gone).

**Comment by unholyeyebrows** [comment]
Thanks for the replies, and to my untrained eye this is certainly not a trivial problem solve by just packing more libraries into the Bitwig flatpak (as I had hoped). Interesting to read the notes on the yabridge initiative to bring compatibility there. Here's hoping if Bitwig intends flatpak to be a primary package format for their DAW then this will drive efforts for the pluigins to be made more compatible. Thanks again.

**Comment by robbert-vdh** [comment]
Theoretically with yabridge 4.x it _should_ sort of just work if you somehow can get both yabridge and Wine running in the same runtime.

**Comment by Lcchy** [comment]
> It's not terribly difficult to add packages on top of the runtime you're using for that very reason.

@drewofdoom I am unable to use a cutom VST in the flatpak Bitwig because of this issue, it would be very helpful if you had any pointers on how to add these dependencies to the flatpak manually.

Or anyone else for that matter :)

Ps: my missing dependency is `/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32'`

**Comment by Lcchy** [comment]
For others with same issue, I found 2 workarounds this far:

- Run Bitwig with `/var/lib/flatpak/app/com.bitwig.BitwigStudio/current/active/files/bitwig-studio` (or whereever your flatpak binary is). This is nearly a solution as it  seems to just work.
- Stop using the flatpak: directly use or repackage the .deb to whatever your distribution uses (I used this script to repackage to .rpm: https://github.com/teervo/bitwig-fedora). works too but is probably less reliable.

**Comment by nikolas** [comment]
How do I add a new library into my flatpak runtime for Bitwig? I want to use the PaulXStretch plugin, and I'm getting the error:

    Failed to load CLAP plug-in ~/.clap/PaulXStretch.clap: libfftw3f.so.3: cannot open shared
    object file: No such file or directory

I've copied my libfftw3f.so.3 file into `/var/lib/flatpak/app/com.bitwig.BitwigStudio/current/active/files/lib/`, and still getting this error.

**Comment by abique** [comment]
> How do I add a new library into my flatpak runtime for Bitwig? I want to use the PaulXStretch plugin, and I'm getting the error:
> 
> ```
> Failed to load CLAP plug-in ~/.clap/PaulXStretch.clap: libfftw3f.so.3: cannot open shared
> object file: No such file or directory
> ```
> 
> I've copied my libfftw3f.so.3 file into `/var/lib/flatpak/app/com.bitwig.BitwigStudio/current/active/files/lib/`, and still getting this error.

This isn't a bitwig issue.
Ask the flatpak team how to solve it, one option would be to statically link xstretch with fftw3.
