### ISSUE TITLE
Missing icons in open file dialog

### ISSUE THREAD

**Issue by abique** [bitwig/bitwig-studio-flatpak#3]

**Comment by abique** [comment]
![image](https://user-images.githubusercontent.com/31200/79054904-29904900-7c49-11ea-9ac8-89b10c7eee1c.png)

**Comment by hfiguiere** [comment]
works fine here.

**Comment by abique** [comment]
So it is a make run issue. Then I can close.

**Comment by hfiguiere** [comment]
Not sure it is related to that though.
