### ISSUE TITLE
Support Audio Plugins

### ISSUE THREAD

**Issue by hfiguiere** [bitwig/bitwig-studio-flatpak#5]
Hi,

I'm filing this ahead of time, but I have been working on way to package audio plugins with flatpak for flathub.

The base package is part of flathub/flathub#1460
Some of the discussion is at https://discourse.flathub.org/t/proposal-for-audio-plugins/399/

Once that PR lands it will basically set how plugins are built (I have a dozen of various kind I tested with that could be published, and a few apps I added support for, including Ardour 6)

The current work is based on the freedesktop SDK 19.08 but I don't see a problem handling 20.08beta (which you are based on)

If you have questions, suggestion, please feel free.

**Comment by abique** [comment]
Hello,
I am quite busy right now, but I'll get back to this soon.

**Comment by abique** [comment]
Thank you very much by the way :)
